"""
Django settings for Tienda project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
from datetime import timedelta
from pathlib import Path

import dj_database_url
from decouple import config
from django.conf.global_settings import AUTHENTICATION_BACKENDS, AUTH_USER_MODEL

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
CORS_ALLOW_ALL_ORIGINS = True
SECRET_KEY = config("SECRET_KEY", "")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG", default=True, cast=bool)
if SECRET_KEY == "":
    raise KeyError("SECRET_KEY cannot be empty")

if DEBUG:
    ALLOWED_HOSTS = ["*"]
else:
    _hosts = config("ALLOWED_HOST", default="")
    ALLOWED_HOSTS = [h.strip() for h in _hosts.split(",") if h.strip()]

CSRF_TRUSTED_ORIGINS = [
    o.strip()
    for o in config("CSRF_TRUSTED_ORIGINS", default="").split(",")
    if o.strip()
]


EXTENSIONES_BLACKLIST = [".ru", ".xyz"]

# Application definition

INSTALLED_APPS = [
    'corsheaders',
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    #REST API
    'rest_framework',
    #Aplicaciones que vayamos creando
    'Users',
    'Productos',
    ]

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),#Tiempo de vida del token
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),#Si se caduca el de arriba este se usa como respaldo para aumentar el tiempo de vida del token
    'ROTATE_REFRESH_TOKENS': False, #Si tuviera True mi sesion se caducaria al iniciar sesion en otro pc
    'BLACKLIST_AFTER_ROTATION': False,#(En True) Si ya existe ese token y se caduca, se guarda en una lista negra para no volver a usarla
    'AUTH_HEADER_TYPES': ('Bearer',)#Es la forma de comunicar el front con el back, para el envio del token
}

#Medidas de seguridad
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'LaParada.urls'

#Para permitir leer archivos HTML
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'LaParada.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Supabase / Postgres: pon DATABASE_URL en .env (Project Settings → Database → URI).
# Para migraciones, usa el host "direct" o puerto 5432 según la documentación de Supabase.
_database_url = config("DATABASE_URL", default="").strip()
if _database_url:
    DATABASES = {
        "default": dj_database_url.parse(
            _database_url,
            conn_max_age=600,
            conn_health_checks=True,
            ssl_require=True,
        )
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'es-ES'

TIME_ZONE = 'Europe/Madrid'
#Traducciones
USE_I18N = True
#Para traducir diccionarios, arrays
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

ASSETS_DIR = BASE_DIR / 'assets'
STATIC_URL = '/static/'
STATICFILES_DIRS = [ASSETS_DIR / 'static']
STATIC_ROOT = ASSETS_DIR / 'collected_static'

if not DEBUG:
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'

MEDIA_URL = '/media/'
MEDIA_ROOT = ASSETS_DIR / 'media'

# En producción (DEBUG=False) sirve /media/ salvo que fuerces SERVE_MEDIA_IN_PRODUCTION=false.
# En Render/Vercel las URLs https correctas requieren cabeceras del proxy:
_serve_media = config("SERVE_MEDIA_IN_PRODUCTION", default="auto").strip().lower()
if _serve_media in ("1", "true", "yes", "on"):
    SERVE_MEDIA_IN_PRODUCTION = True
elif _serve_media in ("0", "false", "no", "off"):
    SERVE_MEDIA_IN_PRODUCTION = False
else:
    SERVE_MEDIA_IN_PRODUCTION = not DEBUG

if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    USE_X_FORWARDED_HOST = True

#Intentar autentificacion
##AUTHENTICATION_BACKENDS = [
##    "Users.backends.EmailOrPhoneBackend",
##    "django.contrib.auth.backends.ModelBackend",
##]

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'Users.Users'

# Logging: en produccion (DEBUG=False) Django no muestra tracebacks de errores 5xx
# por defecto. Esto los redirige a stderr para que aparezcan en los logs de Render.
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "[{levelname}] {asctime} {name} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
    "loggers": {
        "django.request": {
            "handlers": ["console"],
            "level": "ERROR",
            "propagate": False,
        },
        "django.server": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
    },
}